name: ${project.name}
version: ${project.version}
build: ${buildNumber}
main: ${main.class}
author: ${author}
api-version: 1.16

libraries:
  - com.google.code.gson:gson:2.8.6

softdepend:
  - PlaceholderAPI
  - Vault