name: Vouchers
version: maven-version-number
api-version: 1.16
main: ca.tweetzy.vouchers.Vouchers
description: Reedemable vouchers made simple
authors: [Kiran Hart]

commands:
  vouchers:
    description: Main command for the voucher plugin
    aliases: [voucher]
    default: true
    usage: /vouchers
