Confirm Menu:
  Title: "&eConfirm Redeem"
  Rows: 3
  Background Item: BLACK_STAINED_GLASS_PANE
  Confirm Item:
    Slots: [ 14, 15, 16 ]
    Material: LIME_STAINED_GLASS_PANE
    Name: "&a&lConfirm"
    Lore:
      - ""
      - "&dClick &7to confirm redeem"
  Cancel Item:
    Slots: [ 10, 11, 12 ]
    Material: RED_STAINED_GLASS_PANE
    Name: "&c&lCancel"
    Lore:
      - ""
      - "&dClick &7to cancel redeem"


# -------------------------------------------------------------------------------------------------
# The format used in the {timestamp} placeholder (google "Java timestamp format" for options).
# -------------------------------------------------------------------------------------------------
Timestamp_Format: "MMM/dd/yyyy HH:mm:ss aa"

# -------------------------------------------------------------------------------------------------
# * THE FIRST ALIAS IS THE MAIN LABEL, PLEASE DO NOT REMOVE IT. *
# -------------------------------------------------------------------------------------------------
Command_Aliases: [ vouchers, voucher ]

# -------------------------------------------------------------------------------------------------
# What language should we use for messages? If it exists, the language file will be copied
# to your messages/ folder where you can edit it.
# -------------------------------------------------------------------------------------------------
Locale: en

# -------------------------------------------------------------------------------------------------
# The prefix used in front of most chat or console messages
# -------------------------------------------------------------------------------------------------
Prefix: "&8[&eVouchers&8]"

# -------------------------------------------------------------------------------------------------
# We log a console message if an operation takes over the time below (milliseconds).
# Set to -1 to disable.
# -------------------------------------------------------------------------------------------------
Log_Lag_Over_Milis: 100

# -------------------------------------------------------------------------------------------------
# Do not change this value, otherwise it will corrupt your plugin installation!
# -------------------------------------------------------------------------------------------------
Version: 1