Voucher List Menu:
  Title: "&eVouchers"
  Background Item: BLACK_STAINED_GLASS_PANE

Confirm Menu:
  Title: "&eConfirm Redeem"
  Rows: 3
  Background Item: BLACK_STAINED_GLASS_PANE
  Confirm Item:
    Slots: [ 14, 15, 16 ]
    Material: LIME_STAINED_GLASS_PANE
    Name: "&a&lConfirm"
    Lore:
      - ""
      - "&dClick &7to confirm redeem"
  Cancel Item:
    Slots: [ 10, 11, 12 ]
    Material: RED_STAINED_GLASS_PANE
    Name: "&c&lCancel"
    Lore:
      - ""
      - "&dClick &7to cancel redeem"

Reward Select Menu:
  Title: "&eSelect a Reward"
  # If true, vouchers will ignore that reward's chance and always give the user
  # the item they selected
  Always Give: true
  Rows: 3
  Reward Slots: [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 ]
  Background Item: BLACK_STAINED_GLASS_PANE
  Command Item: PAPER
  Command Name: "&e&lCommand Reward"
  Command Lore:
    - ""
    - "&7Command&f: &e{reward_command}"
    - ""
  Command Lore Chance:
    - ""
    - "&7Command&f: &e{reward_command}"
    - "&7Chance&f: &a{reward_chance}&f%"
    - ""

# -------------------------------------------------------------------------------------------------
# * THE FIRST ALIAS IS THE MAIN LABEL, PLEASE DO NOT REMOVE IT. *
# -------------------------------------------------------------------------------------------------
Command_Aliases: [ vouchers, voucher ]

# -------------------------------------------------------------------------------------------------
# What language should we use for messages? If it exists, the language file will be copied
# to your messages/ folder where you can edit it.
# -------------------------------------------------------------------------------------------------
Locale: en

# -------------------------------------------------------------------------------------------------
# The prefix used in front of most chat or console messages
# -------------------------------------------------------------------------------------------------
Prefix: "&8[&eVouchers&8]"

# -------------------------------------------------------------------------------------------------
# We log a console message if an operation takes over the time below (milliseconds).
# Set to -1 to disable.
# -------------------------------------------------------------------------------------------------
Log_Lag_Over_Milis: -1

# -------------------------------------------------------------------------------------------------
# Do not change this value, otherwise it will corrupt your plugin installation!
# -------------------------------------------------------------------------------------------------
Version: 1